site_name: Software Reference Architecture
repo_url: https://github.com/yashesviraina-fev/glossary-site.git
repo_name: glossary-site
edit_uri: ""

nav:
  - Glossary: swrefarch_glossary.md
  - Classic: classic_ref_sw_arch_2022.md
  - SOA: soa_ref_arch_layers.md
  #- Multicore Architecture: classic_multicore_ref_arch.md

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - content.code.annotate
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  palette:
  - scheme: light
    primary: white
    accent: white

  font:
    text: Roboto
    code: Roboto Mono
  logo: ./zf-logo.svg
  favicon: ./zf-logo.svg

extra:
  version:
    provider: mike
    default: latest
  generator: false

extra_css:
  - stylesheet/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - meta
  - mkdocs-click

plugins:
  - mike
  - search